### ISSUE TITLE
Phone on SE Clinton & 13th is down, no dial tone. 

### ISSUE THREAD

**Issue by mihow** [kra/futel#1]
Last time I checked was Thursday October 12th around 6pm.

**Comment by kra** [comment]
Thanks for the report. Either the phone or the line from the house to the phone is broken, a phone connected inside the house works.

**Comment by lboom** [comment]
Gained access to the panel and checked the line to the house. Was able to make a call from a lineman's set. No obvious damage to the phone.

**Comment by kra** [comment]
Replaced phone!
