### ISSUE TITLE
get articles in archive.org and add to links page

### ISSUE THREAD

**Issue by kra** [kra/futel#145]
"Futel utilizes forgotten payphones with free calls for anyone", Street Roots article, February 7, 2024
https://www.streetroots.org/news/2024/02/07/futel-upcycles-pay-phones-free-calls

"Futel: for Whom The Dial Tones", Teardown presentation, June 24, 2023
https://www.crowdsupply.com/teardown/portland-2023/short-talk/futel-for-whom-the-dial-tones

**Comment by breedx2** [comment]
Archive has them:

https://web.archive.org/web/20240215005137/https://www.streetroots.org/news/2024/02/07/futel-upcycles-pay-phones-free-calls

https://web.archive.org/web/20230628182057/https://www.crowdsupply.com/teardown/portland-2023/short-talk/futel-for-whom-the-dial-tones

I added them to the `links.txt` doc.
