### ISSUE TITLE
apply for culturesource creators of culture grant

### ISSUE THREAD

**Issue by kra** [kra/futel#44]
https://www.culturesource.org/resources/creators-of-culture-grants

are located in Wayne, Oakland or Macomb Counties
- will we need a local umbrella org? or maybe this can just be funding the detroit bus co phone?
include payments to creators of culture as part of your project
- we must find local artists and pay them
- can structure this like metro proposal - find artist partners, name them, interview/audio/history/interactive work

You must submit your application by June 10, 2019.

**Comment by ReverendJB** [comment]
Umbrella org ("If you...are located in Wayne, Oakland or Macomb Counties")
– What criteria for local artists? Sound artists? Performance? Conceptual?
– How many local artists?
– What will their role be? 
– How to find them? 
– Paid out of this grant?

**Comment by kra** [comment]
> What criteria for local artists? Sound artists? Performance? Conceptual?

No criteria other than they can work in the medium of a payphone. Just contributing music or words would work! But ideally this would be interactive. Ideally ideally Futel is just the delivery mechanism for the artist and doesn't get in the way, other than tech support and help with the medium. Oral history or survey would work well too. But the only real criterion is a Detroit audio artist. The phones themselves are the draw.

I think a big thing is that they don't want an unconnected artist plunking something down and saying here's your art, enjoy it. In Portland they especially don't want white guys thinking they can provide culture to communities of color.

Here's an example from another proposal.


https://github.com/kra/futel/blob/master/media/proposals/racc2019/application.txt#L10

**Comment by kra** [comment]
If a 501c3 isn't required, the local orgs could be the hosts of the phones. Probably Detroit Bus Co and Eight and Sand. That's enough for a small grant.

**Comment by kra** [comment]
Yes, artists are paid from the grant. How to find them is the big question. I'm asking around but TBH I'm relying on others who have the connections that I don't. If we don't get names we can just say local artists TBD, although the proposal would be much weaker.

See recent proposals for budget examples etc. Could put a draft together for this proposal by stitching parts of the most recent 2 or 3 proposals and iterating on that to make a final version.

https://github.com/kra/futel/tree/master/media/proposals

**Comment by ReverendJB** [comment]
Hi Karl,

Is it preferred to communicate RE: this grant on Git Hub? I'm new to the
platform not having any coding experience.
I have done some searches that I would expect to generate relevant results
in other cities, but have had little luck locating artist hubs in that area
of Michigan. yet.
Focusing on Detroit seems like a way to hone in on artist collectives and
groups. One I am familiar with is Trumble Theater, now DBA Trumbleplex.
This would actually be a decent location for a Futel phone. They have
acquired more property around two large houses, that are kept open to the
public and maintained as public spaces. Anarcho-arts collective.
https://trumbullplex.org/about/

- JB

**Comment by ReverendJB** [comment]
Arts Collective, DETROIT: 
Call (248) 212-2594
m.me/detroitartcollective

About: Detroit Art Collective (DAC) = A Non-Profit Organization Of Artists Giving Back To The Community Though Art. DAC Utilizes Creative & Innovative Methods Raising Awareness To The Public RE: Issues We Face Daily.
DETROIT ART COLLECTIVE. Russell Industrial. 1600 Clay Street, Building One, Suite 222 - 248.703.2369
