### ISSUE TITLE
"domestic telephone calls"

### ISSUE THREAD

**Issue by kra** [kra/futel#52]
change wording of "domestic telephone calls" in various media to just "telephone calls"

eg

At Futel, we believe in the preservation of public telephone hardware as a means of providing access to the agora for everybody, and toward that goal we are privileged to provide free domestic telephone calls, voicemail, and telephone-mediated services.

also open corresponding issues in futel.net to update text, or just fix it

**Comment by breedx2** [comment]
The changes were made in futel.net in 079859ca8194d26c177cfa22e3e30673d90f7fe3 https://github.com/kra/futel.net/commit/079859ca8194d26c177cfa22e3e30673d90f7fe3#diff-4038b616b763c64f63837e70b0cba34a

**Comment by breedx2** [comment]
All of the other references to "domestic" were in (past?) proposals or talk notes.
