### ISSUE TITLE
archive external publicity

### ISSUE THREAD

**Issue by kra** [kra/futel#56]
get every link to interviews articles etc into archive.org
download what can't go in there
collect both original and archive link eg in cv

**Comment by breedx2** [comment]
How are you envisioning this?  One idea is to download all the content and then re-upload to archive.org and create a new item for each source.  Another idea is to get the pages indexed/archived by the wayback machine, which now looks to have a convenient box for doing this like this:
![image](https://user-images.githubusercontent.com/1888255/71540880-3fca0180-2905-11ea-9f8f-6a330727772c.png)

Is that more like what you were thinking?

One immediate issue is that the "save page now" (on archive.org) won't work well for highly dynamic modern sites.  For instance, I had it do the NPR page for the piece today and it looks good but the download link for the audio is broken.  There are likely to be other/similar challenges for other resources.

**Comment by kra** [comment]
envisioning this, right, yeah. Yeah, run the tool on the original external links and get a list of external links and archive links. Document the process, it can be manual. Save the list, probably here:

https://github.com/kra/futel/blob/master/media/proposals/general/links.txt

Best source for links is probably the blog.

BTW this should be updated with the new content.
https://github.com/kra/futel.net/issues/36
