### ISSUE TITLE
add these links to media page

### ISSUE THREAD

**Issue by kra** [kra/futel#66]
https://www.metrotimes.com/news-hits/archives/2020/03/04/a-second-free-payphone-is-coming-to-detroit
https://www.wweek.com/culture/2020/02/12/a-portland-software-engineer-is-bringing-the-pay-phone-back-minus-the-pay-part/

add to links page, add to archive.org

**Comment by breedx2** [comment]
The archive part is done:

https://web.archive.org/web/20200307044433/https://www.wweek.com/culture/2020/02/12/a-portland-software-engineer-is-bringing-the-pay-phone-back-minus-the-pay-part/

https://web.archive.org/web/20200307044526/https://www.metrotimes.com/news-hits/archives/2020/03/04/a-second-free-payphone-is-coming-to-detroit
