### ISSUE TITLE
put party line #5 in archive.org

### ISSUE THREAD

**Issue by kra** [kra/futel#67]
also are issues 1-4 in there?

**Comment by breedx2** [comment]
The first issues _are_ in there, but they're all part of a single item.
https://archive.org/download/partyline.indd

I think it would be preferable to have them uploaded to the archive as separate items.

**Comment by kra** [comment]
yeah that upload is bullshit, we should duplicate its content
one archive.org entry per issue
pdfs only
booklet format and screen format in the same entry?

**Comment by breedx2** [comment]
I created these:
https://archive.org/details/futel_partyline_2016
https://archive.org/details/futel_partyline_2017
https://archive.org/details/futel_partyline_2018
https://archive.org/details/futel_partyline_2019
https://archive.org/details/futel_partyline_2020

@kra You own the original upload linked above and will need to remove it (if desired).  I have no idea how you managed to get it into the zines collection...it's not user-selectable nor user-changeable.  We could email and ask if it matters.
