### ISSUE TITLE
decide how to implement per extension usage visualizer

### ISSUE THREAD

**Issue by kra** [kra/futel#86]
we need a plot of usage per extension over time
the goal is to see how much use each extension gets over a period

for example:
x axis: time
y axis: events
one line for each extension

events can be total events, or total selected events
graphs can be stacked or overlaid

I had assumed that futel-usage-viz would be how this was implemented, but breedx was saying that this had a lot of bespoke javascript and we could do better with free usage of more appropriate tools

this will help monitor downtime
the mechaoperator "recentstats" command is how I currently do this but it takes too much thought

**Comment by breedx2** [comment]
How timely do you want it?  Is daily enough, or how quickly should telemetry be updated?

I think there should be another issue first about exfiltrating telemetry.  Once that's done, we can look into making charts/dataviz.

The futel-usage-viz was based on some static filtered data...which is fine, as long as there is build automation to get it into place.  IMO, the primary thing should first be getting the data safely/securely out of the garden. Ideally, this would be something kinda semi-continuous, hourly or daily spring to mind.  Github actions go a long way to help with this these days.  Enumerable s3 bucket is also a popular option, but giving hosting, might having cors/xss/proxy considerations.

Hosting via github pages is also fine, but it kinda means getting the data back into github.  Also fine, and actions can help.  The data sets are small enough that I'd be kinda into folding back into github and keeping it single-source.

**Comment by kra** [comment]
the exfiltration issue is https://github.com/kra/futel-installation/issues/418
That says to use s3 because that's what we discussed over signal, but we don't have use s3 if you have a better idea. But the good thing about s3 is that both ends only need aws creds. I don't know github actions, but if we can get safe creds for that we can use that. Something where when the boxen get popped the repos are safe.

I am assuming that the consumer end is working off of files that are reconstructed off of the transport, and that transport and visualization can be separate issues.

Hourly is good, daily is fine.
