### ISSUE TITLE
submit party line #6 to internet archive

### ISSUE THREAD

**Issue by kra** [kra/futel#88]

**Comment by breedx2** [comment]
It's uploaded: https://archive.org/details/futel_partyline_2021

There's no obvious way to control if/how/when it gets migrated to the "zine" collection, but all the other ones did and this one probably will too.  I say we leave this issue open for a few days or weeks and check back to see if it gets converted.

**Comment by lboom** [comment]
verified that it has been added to the "zines" collection.
